# Generated by Django 3.1.4 on 2021-01-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='detail',
            new_name='fullDescription',
        ),
        migrations.AddField(
            model_name='news',
            name='shortDescription',
            field=models.TextField(default='', max_length=200, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='News title'),
        ),
    ]
